//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InterviewPanel
    {
        public int PanelId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> CandidateDeptId { get; set; }
        public string CandidateDesignations { get; set; }
        public string SecondarySkills { get; set; }
        public string LevelIds { get; set; }
        public Nullable<int> Inducted { get; set; }
        public Nullable<int> TrainingAttended { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
