//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SubDomain
    {
        public int ID { get; set; }
        public string SubDomainName { get; set; }
        public int DomainID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual T_Domain T_Domain { get; set; }
    }
}
